// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sankabinis.Data;

#nullable disable

namespace Sankabinis.Migrations
{
    [DbContext(typeof(SankabinisContext))]
    [Migration("20240524151235_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sankabinis.Models.Achievement", b =>
                {
                    b.Property<int>("Id_Pasiekimas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pasiekimas"));

                    b.Property<string>("Aprasas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Pasiekimas");

                    b.ToTable("pasiekimas");
                });

            modelBuilder.Entity("Sankabinis.Models.Car", b =>
                {
                    b.Property<int>("Id_Automobilis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Automobilis"));

                    b.Property<int>("Fk_Naudotojasid_Naudotojas")
                        .HasColumnType("int");

                    b.Property<int>("Galingumas")
                        .HasColumnType("int");

                    b.Property<int>("Kebulas")
                        .HasColumnType("int");

                    b.Property<int>("Klase")
                        .HasColumnType("int");

                    b.Property<int>("Kuro_tipas")
                        .HasColumnType("int");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numeris")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("Pagaminimo_data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pavaru_deze")
                        .HasColumnType("int");

                    b.Property<int>("Rida")
                        .HasColumnType("int");

                    b.Property<string>("Spalva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Svoris")
                        .HasColumnType("float");

                    b.HasKey("Id_Automobilis");

                    b.ToTable("automobilis");
                });

            modelBuilder.Entity("Sankabinis.Models.City", b =>
                {
                    b.Property<int>("Id_Miestas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Miestas"));

                    b.Property<string>("Koordinates")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Miestas");

                    b.ToTable("miestas");
                });

            modelBuilder.Entity("Sankabinis.Models.Complaint", b =>
                {
                    b.Property<int>("Id_Skundas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Skundas"));

                    b.Property<int>("Id_Lenktynes")
                        .HasColumnType("int");

                    b.Property<string>("Paaiskinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Sukurimo_Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Uzdarytas")
                        .HasColumnType("bit");

                    b.HasKey("Id_Skundas");

                    b.ToTable("skundas");
                });

            modelBuilder.Entity("Sankabinis.Models.Distance", b =>
                {
                    b.Property<int>("Id_Atstumas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Atstumas"));

                    b.Property<double>("Atstumas")
                        .HasColumnType("float");

                    b.Property<int>("CityId1")
                        .HasColumnType("int");

                    b.Property<int>("CityId2")
                        .HasColumnType("int");

                    b.HasKey("Id_Atstumas");

                    b.ToTable("atstumas");
                });

            modelBuilder.Entity("Sankabinis.Models.Race", b =>
                {
                    b.Property<int>("Id_Lenktynes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Lenktynes"));

                    b.Property<bool>("Antro_naudotojo_patvirtinimas")
                        .HasColumnType("bit");

                    b.Property<int>("Automobilio_klase")
                        .HasColumnType("int");

                    b.Property<bool>("Pirmo_naudotojo_patvirtinimas")
                        .HasColumnType("bit");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.Property<bool>("ar_galutinis_rezultatas")
                        .HasColumnType("bit");

                    b.Property<bool>("ar_laikas_patvirtintas")
                        .HasColumnType("bit");

                    b.Property<bool>("ar_lenktynes_pasibaigusios")
                        .HasColumnType("bit");

                    b.Property<DateTime>("pasiulytas_laikas")
                        .HasColumnType("datetime2");

                    b.Property<int>("rezultatas_pagal_antraji_naudotoja")
                        .HasColumnType("int");

                    b.Property<int>("rezultatas_pagal_pirmaji_naudotoja")
                        .HasColumnType("int");

                    b.HasKey("Id_Lenktynes");

                    b.ToTable("lenktynes");
                });

            modelBuilder.Entity("Sankabinis.Models.Track", b =>
                {
                    b.Property<int>("Id_Trasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Trasa"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("finish_coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("start_coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Trasa");

                    b.ToTable("trasa");
                });

            modelBuilder.Entity("Sankabinis.Models.User", b =>
                {
                    b.Property<int>("Id_Naudotojas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Naudotojas"));

                    b.Property<string>("Busena")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("El_pastas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Elo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Gimimo_data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Laimėta_lenktyniu")
                        .HasColumnType("int");

                    b.Property<int>("Lenktyniu_skaicius")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Lytis")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Pasitikimo_taskai")
                        .HasColumnType("int");

                    b.Property<DateTime>("Paskutinio_prisijungimo_data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Paskyros_sukurimo_data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Patirtis")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Pralaimėta_lenktyniu")
                        .HasColumnType("int");

                    b.Property<string>("Slaptazodis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slapyvardis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Suspeduotos_busenos_skaicius")
                        .HasColumnType("int");

                    b.Property<double>("Svoris")
                        .HasColumnType("float");

                    b.Property<string>("Vardas_pavarde")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Naudotojas");

                    b.ToTable("naudotojas");
                });
#pragma warning restore 612, 618
        }
    }
}
